### ISSUE TITLE
Missing file "Preproccess.preprocessing"

### ISSUE THREAD

**Issue by kunwu522** [BUPT-GAMMA/MiBTack#1]
It seems there is a missing file.

Traceback (most recent call last):
  File "MiBTack.py", line 6, in <module>
    from Preprocess.preprocessing import *
ModuleNotFoundError: No module named 'Preprocess.preprocessing'

**Comment by MengmeiZ** [comment]
Thank you for your attention to our work. I have already uploaded the relevant files.
